Repository Junhan0037/spring-react-security, pull requests merged in 2022-01, with the labels that each got.

#4 Spring Boot + React 환경 구축
  .gitignore
  README.md
  build.gradle
  images/img_1.png
  images/img_2.png
  images/img_3.png
  src/main/java/com/springreactsecurity/common/BaseTimeEntity.java
  src/main/java/com/springreactsecurity/common/CustomErrorController.java
  src/main/java/com/springreactsecurity/config/AppConfig.java
  src/main/java/com/springreactsecurity/config/JpaConfig.java
  src/main/java/com/springreactsecurity/config/SecurityConfig.java
  src/main/java/com/springreactsecurity/config/p6spy/P6spyConfig.java
  src/main/java/com/springreactsecurity/config/p6spy/P6spyPrettySqlFormatter.java
  src/main/java/com/springreactsecurity/config/swagger/SpringFoxConfig.java
  src/main/java/com/springreactsecurity/exception/BaseException.java
  src/main/java/com/springreactsecurity/exception/ControllerExceptionHandler.java
  src/main/java/com/springreactsecurity/exception/ErrorResponseDto.java
  src/main/java/com/springreactsecurity/exception/MsgType.java
  src/main/java/com/springreactsecurity/jasypt/JspytGenerator.java
  src/main/resources/application-local.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/webapp/.gitignore
  src/main/webapp/README.md
  src/main/webapp/package-lock.json
  src/main/webapp/package.json
  src/main/webapp/public/favicon.ico
  src/main/webapp/public/index.html
  src/main/webapp/public/logo192.png
  src/main/webapp/public/logo512.png
  src/main/webapp/public/manifest.json
  src/main/webapp/public/robots.txt
  src/main/webapp/src/App.css
  src/main/webapp/src/App.test.tsx
  src/main/webapp/src/App.tsx
  src/main/webapp/src/index.css
  src/main/webapp/src/index.tsx
  src/main/webapp/src/logo.svg
  src/main/webapp/src/react-app-env.d.ts
  src/main/webapp/src/reportWebVitals.ts
  src/main/webapp/src/setupTests.ts
  src/main/webapp/tsconfig.json
Labels: feat

#6 Spring Security 설정, 회원가입 API
  build.gradle
  src/main/java/com/springreactsecurity/config/SecurityConfig.java
  src/main/java/com/springreactsecurity/domain/member/Member.java
  src/main/java/com/springreactsecurity/domain/member/MemberController.java
  src/main/java/com/springreactsecurity/domain/member/MemberRepository.java
  src/main/java/com/springreactsecurity/domain/member/MemberService.java
  src/main/java/com/springreactsecurity/domain/member/MemberServiceImpl.java
  src/main/java/com/springreactsecurity/domain/member/Role.java
  src/main/java/com/springreactsecurity/domain/member/dto/MemberDto.java
  src/main/java/com/springreactsecurity/exception/AccountException.java
  src/main/java/com/springreactsecurity/exception/ControllerExceptionHandler.java
  src/main/java/com/springreactsecurity/exception/MsgType.java
  src/main/java/com/springreactsecurity/security/CurrentUser.java
  src/main/java/com/springreactsecurity/security/CurrentUserInfoUtil.java
  src/main/java/com/springreactsecurity/security/SecurityConfig.java
  src/main/java/com/springreactsecurity/security/UserMember.java
  src/main/java/com/springreactsecurity/security/handler/LoginAccessDeniedHandler.java
  src/main/java/com/springreactsecurity/security/handler/LoginAuthenticationEntryPoint.java
  src/main/java/com/springreactsecurity/security/handler/LoginFailureHandler.java
  src/main/java/com/springreactsecurity/security/handler/LoginSuccessHandler.java
  src/main/java/com/springreactsecurity/security/handler/LogoutSuccessHandler.java
  src/main/resources/application-local.yml
Labels: feat

#7 Spring Security RememberMe
  build.gradle
  src/main/java/com/springreactsecurity/common/BaseTimeEntity.java
  src/main/java/com/springreactsecurity/config/AppConfig.java
  src/main/java/com/springreactsecurity/domain/member/Member.java
  src/main/java/com/springreactsecurity/domain/member/MemberServiceImpl.java
  src/main/java/com/springreactsecurity/security/PersistentLogins.java
  src/main/java/com/springreactsecurity/security/SecurityConfig.java
  src/main/java/com/springreactsecurity/security/UserDetailServiceImpl.java
  src/main/java/com/springreactsecurity/security/handler/LoginAccessDeniedHandler.java
  src/main/java/com/springreactsecurity/security/handler/LoginAuthenticationEntryPoint.java
  src/main/java/com/springreactsecurity/security/handler/LoginFailureHandler.java
  src/main/java/com/springreactsecurity/security/handler/LoginSuccessHandler.java
  src/main/java/com/springreactsecurity/security/handler/LogoutSuccessHandler.java
Labels: feat

#12 Security, 회원 정보 찾기
  README.md
  src/main/java/com/springreactsecurity/domain/member/Member.java
  src/main/java/com/springreactsecurity/domain/member/MemberController.java
  src/main/java/com/springreactsecurity/domain/member/MemberRepository.java
  src/main/java/com/springreactsecurity/domain/member/MemberService.java
  src/main/java/com/springreactsecurity/domain/member/MemberServiceImpl.java
  src/main/java/com/springreactsecurity/domain/member/dto/MemberDto.java
  src/main/java/com/springreactsecurity/domain/member/dto/MemberRequestDto.java
  src/main/java/com/springreactsecurity/domain/member/dto/MemberResponseDto.java
  src/main/java/com/springreactsecurity/exception/ControllerExceptionHandler.java
  src/main/java/com/springreactsecurity/security/SecurityConfig.java
  src/main/java/com/springreactsecurity/security/UserDetailServiceImpl.java
  src/main/java/com/springreactsecurity/security/UserMember.java
  src/main/java/com/springreactsecurity/security/handler/AccessDeniedHandler.java
  src/main/java/com/springreactsecurity/security/handler/AuthenticationEntryPoint.java
  src/main/java/com/springreactsecurity/security/handler/LoginSuccessHandler.java
Labels: feat, fix

#14 feat: 로그인, 로그아웃 #13
  src/main/webapp/package-lock.json
  src/main/webapp/package.json
  src/main/webapp/src/App.tsx
  src/main/webapp/src/components/SignIn.tsx
  src/main/webapp/src/containers/SignInContainer.tsx
  src/main/webapp/src/history.ts
  src/main/webapp/src/index.tsx
  src/main/webapp/src/pages/ErrorPage.tsx
  src/main/webapp/src/pages/HomePage.tsx
  src/main/webapp/src/pages/SignInPage.tsx
  src/main/webapp/src/redux/create.ts
  src/main/webapp/src/redux/modules/auth.ts
  src/main/webapp/src/redux/modules/index.ts
  src/main/webapp/src/redux/modules/rootSaga.ts
  src/main/webapp/src/services/TokenService.ts
  src/main/webapp/src/services/UserService.ts
  src/main/webapp/src/services/client.ts
  src/main/webapp/src/types.ts
Labels: feat, fix

#16 SMTP
  README.md
  build.gradle
  src/main/java/com/springreactsecurity/domain/member/MemberServiceImpl.java
  src/main/java/com/springreactsecurity/exception/ControllerExceptionHandler.java
  src/main/java/com/springreactsecurity/exception/CustomErrorController.java
  src/main/java/com/springreactsecurity/exception/MailException.java
  src/main/java/com/springreactsecurity/exception/MsgType.java
  src/main/java/com/springreactsecurity/mail/EmailMessage.java
  src/main/java/com/springreactsecurity/mail/EmailService.java
  src/main/java/com/springreactsecurity/mail/EmailServiceImpl.java
  src/main/java/com/springreactsecurity/swagger/SpringFoxConfig.java
  src/main/resources/application-local.yml
  src/main/resources/templates/mail/simple-link.html
Labels: feat

#17 회원 정보 출력, 개인 정보 수정 API
  src/main/java/com/springreactsecurity/domain/member/MemberController.java
  src/main/java/com/springreactsecurity/domain/member/MemberService.java
  src/main/java/com/springreactsecurity/domain/member/MemberServiceImpl.java
  src/main/java/com/springreactsecurity/domain/member/dto/MemberDto.java
  src/main/java/com/springreactsecurity/domain/member/dto/MemberResponseDto.java
  src/main/java/com/springreactsecurity/security/UserDetailServiceImpl.java
Labels: feat

#18 Swagger 오류 수정
  README.md
  src/main/java/com/springreactsecurity/security/SecurityConfig.java
Labels: fix

#20 Sandbox yeboong
  src/main/webapp/package-lock.json
  src/main/webapp/package.json
  src/main/webapp/src/App.tsx
  src/main/webapp/src/components/SignIn.tsx
  src/main/webapp/src/pages/BDCrewPage.tsx
  src/main/webapp/src/pages/BDPage.tsx
  src/main/webapp/src/pages/FindPasswordPage.tsx
  src/main/webapp/src/pages/JippaguiPage.tsx
  src/main/webapp/src/pages/SignUpPage.tsx
  src/main/webapp/src/services/UserService.ts
  src/main/webapp/src/types.ts
Labels: feat, fix

#23 사용자 - 비밀번호 수정
  README.md
  src/main/java/com/springreactsecurity/domain/member/MemberController.java
  src/main/java/com/springreactsecurity/domain/member/MemberService.java
  src/main/java/com/springreactsecurity/domain/member/MemberServiceImpl.java
  src/main/java/com/springreactsecurity/domain/member/dto/MemberDto.java
  src/main/java/com/springreactsecurity/exception/ControllerExceptionHandler.java
Labels: feat, fix

#28 fix: BE API Exception response 객체 문제 해결 #25
  src/main/webapp/package-lock.json
  src/main/webapp/src/components/SignIn.tsx
  src/main/webapp/src/containers/SignInContainer.tsx
  src/main/webapp/src/lib/api/auth.ts
  src/main/webapp/src/redux-saga/create.ts
  src/main/webapp/src/redux-saga/modules/auth.ts
  src/main/webapp/src/types.ts
Labels: fix

#31 feat: 로딩 페이지 #24
  src/main/webapp/package-lock.json
  src/main/webapp/package.json
  src/main/webapp/src/App.tsx
  src/main/webapp/src/components/Loading.tsx
  src/main/webapp/src/components/SignIn.tsx
  src/main/webapp/src/containers/SignInContainer.tsx
  src/main/webapp/src/pages/HomePage.tsx
  src/main/webapp/src/redux-saga/create.ts
  src/main/webapp/src/redux-saga/modules/auth.ts
  src/main/webapp/src/types.ts
Labels: feat

#36 feat: copyright 페이지 이미지 추가 #19
  src/main/webapp/public/BDCrew10.jpg
  src/main/webapp/public/BDCrew11.jpg
  src/main/webapp/public/BDCrew12.jpg
  src/main/webapp/public/BDCrew13.jpg
  src/main/webapp/public/BDCrew14.jpg
  src/main/webapp/public/BDCrew15.jpg
  src/main/webapp/public/BDCrew16.jpg
  src/main/webapp/public/BDCrew17.jpg
  src/main/webapp/public/BDCrew18.jpg
  src/main/webapp/public/BDCrew19.jpg
  src/main/webapp/public/BDCrew20.png
  src/main/webapp/public/BDCrew21.jpg
  src/main/webapp/public/BDCrew22.jpg
  src/main/webapp/public/BDCrew23.jpg
  src/main/webapp/public/BDCrew24.jpg
  src/main/webapp/public/BDCrew25.jpg
  src/main/webapp/public/BDCrew26.jpg
  src/main/webapp/public/BDCrew7.jpg
  src/main/webapp/public/BDCrew8.jpg
  src/main/webapp/public/BDCrew9.jpg
Labels: feat

#37 fix: copyright 페이지 수정 #19
  src/main/webapp/src/components/Loading.tsx
  src/main/webapp/src/pages/BDCrewPage.tsx
Labels: fix

#39 fix: 로딩 페이지 수정 #24
  src/main/webapp/package-lock.json
  src/main/webapp/package.json
  src/main/webapp/src/App.tsx
  src/main/webapp/src/pages/BDCrewPage.tsx
Labels: fix

#40 이메일 인증 API
  src/main/java/com/springreactsecurity/core/exception/ErrorType.java
  src/main/java/com/springreactsecurity/core/mail/EmailMessage.java
  src/main/java/com/springreactsecurity/core/mail/EmailService.java
  src/main/java/com/springreactsecurity/core/mail/EmailServiceImpl.java
  src/main/java/com/springreactsecurity/core/security/UserDetailServiceImpl.java
  src/main/java/com/springreactsecurity/core/security/handler/LoginSuccessHandler.java
  src/main/java/com/springreactsecurity/domain/member/Member.java
  src/main/java/com/springreactsecurity/domain/member/repository/MemberRepository.java
  src/main/java/com/springreactsecurity/domain/member/service/MemberService.java
  src/main/java/com/springreactsecurity/domain/member/service/MemberServiceImpl.java
  src/main/java/com/springreactsecurity/web/CurrentUserInfoUtil.java
  src/main/java/com/springreactsecurity/web/MemberController.java
  src/main/resources/templates/mail/simple-link.html
Labels: feat, fix

#41 관리자 API
  src/main/java/com/springreactsecurity/core/exception/ErrorType.java
  src/main/java/com/springreactsecurity/core/security/SecurityConfig.java
  src/main/java/com/springreactsecurity/domain/admin/Admin.java
  src/main/java/com/springreactsecurity/domain/admin/dto/AdminDto.java
  src/main/java/com/springreactsecurity/domain/admin/service/AdminService.java
  src/main/java/com/springreactsecurity/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/springreactsecurity/domain/member/service/MemberService.java
  src/main/java/com/springreactsecurity/domain/member/service/MemberServiceImpl.java
  src/main/java/com/springreactsecurity/web/AdminController.java
  src/main/java/com/springreactsecurity/web/CurrentUserInfoUtil.java
  src/main/java/com/springreactsecurity/web/MemberController.java
  src/main/resources/application-local.yml
Labels: feat

#44 feat: BDCrew Photo History Update #19
  src/main/webapp/public/BDCrew27.jpg
  src/main/webapp/public/BDCrew28.jpg
  src/main/webapp/public/BDCrew29.jpg
  src/main/webapp/public/BDCrew30.jpg
  src/main/webapp/public/BDCrew31.png
  src/main/webapp/public/BDCrew32.jpg
  src/main/webapp/public/BDCrew33.jpg
  src/main/webapp/public/BDCrew34.jpg
  src/main/webapp/public/BDCrew35.png
  src/main/webapp/public/BDCrew36.webp
  src/main/webapp/public/BDCrew37.jpg
  src/main/webapp/public/BDCrew38.jpg
  src/main/webapp/src/components/SignUp.tsx
Labels: feat

#48 Docker, 세션 유지 시간
  Dockerfile
  README.md
  build.gradle
  src/main/java/com/springreactsecurity/core/security/SecurityConfig.java
  src/main/java/com/springreactsecurity/core/security/handler/LogoutSuccessHandler.java
  src/main/resources/application-local.yml
Labels: feat, fix

#49 feat: BDCrew Photo History Update #19
  src/main/webapp/src/pages/BDCrewPage.tsx
Labels: feat

#51 feat: 회원가입 #27
  src/main/webapp/package-lock.json
  src/main/webapp/src/components/SignIn.tsx
  src/main/webapp/src/components/SignUp.tsx
  src/main/webapp/src/containers/SignInContainer.tsx
  src/main/webapp/src/containers/SignUpContainer.tsx
  src/main/webapp/src/lib/api/auth.ts
  src/main/webapp/src/pages/SignUpPage.tsx
  src/main/webapp/src/redux-saga/create.ts
  src/main/webapp/src/redux-saga/modules/auth.ts
  src/main/webapp/src/types.ts
Labels: feat, fix

#55 회원가입 시 이메일 중복 검사
  src/main/java/com/springreactsecurity/core/exception/ErrorType.java
  src/main/java/com/springreactsecurity/domain/member/service/MemberServiceImpl.java
Labels: feat

#56 fix: 회원 가입 FE 에러 핸들링 수정 #52
  src/main/webapp/package-lock.json
  src/main/webapp/package.json
  src/main/webapp/src/components/SignUp.tsx
  src/main/webapp/src/containers/SignUpContainer.tsx
  src/main/webapp/src/redux-saga/create.ts
  src/main/webapp/src/redux-saga/modules/auth.ts
  src/main/webapp/src/types.ts
Labels: fix

#57 feat: BDCRew Photo History Update #19
  src/main/webapp/public/BDCrew2.jpg
  src/main/webapp/public/BDCrew39.jpg
  src/main/webapp/public/BDCrew40.jpg
  src/main/webapp/public/BDCrew41.jpg
  src/main/webapp/src/pages/BDCrewPage.tsx
Labels: feat

#58 fix: 에러 처리 UI 개선 #50
  src/main/webapp/src/components/Copyright.tsx
  src/main/webapp/src/components/SignIn.tsx
  src/main/webapp/src/components/SignUp.tsx
  src/main/webapp/src/containers/SignInContainer.tsx
  src/main/webapp/src/containers/SignUpContainer.tsx
  src/main/webapp/src/lib/api/auth.ts
  src/main/webapp/src/pages/HomePage.tsx
  src/main/webapp/src/redux-saga/modules/auth.ts
  src/main/webapp/src/types.ts
Labels: fix
